project:
  type: website
  output-dir: docs

website:
  title: "Jaeseok Hwang"
  site-url: https://jaeseokh.github.io/
  open-graph: true
  back-to-top-navigation: true
  google-analytics: "G-XZWWMRXM72"
  sidebar:
    style: "docked"  # Docked sidebar on the left
    background: "#13294B"  # Navy Blue background
    text-color: "#FF5A00"  # Illinois Orange text color
    search: true  # Include a search bar
    contents:
      - text: "About"
        href: about/index.qmd
      - text: "Resume"
        href: Resume.qmd
      - text: "Research"
        href: research/index.qmd
      - text: "Essays"
        href: essays/

format:
  html:
    theme: yeti
    css: styles.scss  # Custom CSS for styling
    mainfont: sans-serif
    fontsize: 16px
    page-layout: full  # Use the "full" layout to manually implement the sidebar
