project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - webpage_layout.qmd
    - about/index.qmd
    - research/index.qmd
    - research/working_papers.qmd
    - resume/index.qmd
    - resume/*.qmd
    # (add any other specific .qmd you want rendered here)

website:
  title: "Mainpage"
  search: true
  repo-url: https://github.com/jaeseokh/jaeseokh.github.io
  repo-actions: [source, issue]
  page-footer:
    center: "© {2025} used quarto for this webpage"
  navbar:
    right:
      - text: Portfolio
        href: https://jaeseokh.github.io/#projects
      - text: Research
        href: research/index.html
      - text: Resume
        href: resume/index.html

format:
  html:
    theme: cosmo
    toc: false
    css: assets/styles.css
    code-link: true
    smooth-scroll: true

# freeze HTML so unchanged pages don’t rebuild every time
freeze: auto

# make /assets available to subprojects during render
resources:
  - assets
